### ISSUE TITLE
Example was broken. And support for Android Studio.

### ISSUE THREAD

**Issue by leasses** [gudzpoz/luajava#13]
Could you please make a LuaJIT example with Android Studio?

And when I ran the examples, I got an expection:
```

C:\Users\Administrator>java -jar D:\Downloads\Misc\example-all.jar
Lua Version: jit
Exception in thread "main" java.lang.UnsatisfiedLinkError: Unable to find natives or init
        at party.iroiro.luajava.LuaJit.getNatives(LuaJit.java:24)
        at party.iroiro.luajava.LuaJit.<init>(LuaJit.java:11)
        at party.iroiro.luajava.Console.getLua(Console.java:87)
        at party.iroiro.luajava.Console.startInteractive(Console.java:39)
        at party.iroiro.luajava.Console.main(Console.java:31)

```

But if I try the other lua versions, it works.

**Comment by gudzpoz** [comment]
Thank you for reporting! This should have been fixed by https://github.com/gudzpoz/luajava/commit/d3aef0405fb4c85ec164c5218a3698089a6ecc0d. Could you please try again with [the snapshot build](https://github.com/gudzpoz/luajava/actions/runs/2662582078)? The `example-all.jar` can be found by unpacking [the `example.zip` artifact](https://github.com/gudzpoz/luajava/suites/7336579140/artifacts/297184772).

**Comment by leasses** [comment]
Well, the example was fixed. But there are still some problems to support Android Studio, so I want to new an issue and close this one.
