### ISSUE TITLE
NullPointerException throws when pass a jclass to java.proxy.

### ISSUE THREAD

**Issue by leasses** [gudzpoz/luajava#17]
This is the full log of the console:
```
>>> local ActionListener= java.import("java.awt.event.ActionListener")
>>> java.proxy(ActionListener, { windowClosing = function (this, ev) end } )
Exception in thread "main" java.lang.RuntimeException: java.lang.NullPointerException: Cannot invoke "String.endsWith(String)" because "name" is null
        at party.iroiro.luajava.Console.startInteractive(Console.java:72)
        at party.iroiro.luajava.Console.main(Console.java:31)
Caused by: java.lang.NullPointerException: Cannot invoke "String.endsWith(String)" because "name" is null
        at party.iroiro.luajava.util.ClassUtils.forName(ClassUtils.java:188)
        at party.iroiro.luajava.JuaAPI.proxy(JuaAPI.java:35)
        at party.iroiro.luajava.LuaJitNatives.luaL_dostring(Native Method)
        at party.iroiro.luajava.AbstractLua.run(AbstractLua.java:477)
        at party.iroiro.luajava.Console.startInteractive(Console.java:64)
        ... 1 more
```
I see the document, it says the first parameter of  `java.proxy` can pass any one of the `jobj`, `string` and `jclass`. But I tried all of them, only `string` can run successful.

**Comment by gudzpoz** [comment]
Fixed. Thanks!
