### ISSUE TITLE
How to pass a table to java ???

### ISSUE THREAD

**Issue by lingbl** [gudzpoz/luajava#81]
java code:         import tech.tablesaw.api.StringColumn;
                         StringColumn.create("age", {"2","3","4"});
luajava code:   java.import("tech.tablesaw.api.StringColumn"); 
                        strColumn = StringColumn:create("age",{"2","3","4"});

Return by luajava: 

party.iroiro.luajava.LuaException: method not implemented: public abstract void java.util.stream.Stream.forEach(java.util.function.Consumer)
Last Java side exception:
party.iroiro.luajava.LuaException: method not implemented: public abstract void java.util.stream.Stream.forEach(java.util.function.Consumer)
        at party.iroiro.luajava.LuaProxy.callObjectDefault(LuaProxy.java:117)
        at party.iroiro.luajava.LuaProxy.callDefaultMethod(LuaProxy.java:104)
        at party.iroiro.luajava.LuaProxy.invoke(LuaProxy.java:62)
        at com.sun.proxy.$Proxy1.forEach(Unknown Source)
        at tech.tablesaw.api.StringColumn.create(StringColumn.java:107)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)

my luajava code is wrong ?

**Comment by gudzpoz** [comment]
The method call is calling `StringColumn::create(String, tech.tablesaw.columns.strings.DictionaryMap)`. You will need to use `java.method` to call `StringColumn::create(String name, Collection<String> strings)`.

P.S. Please use ` ``` ` to format your code if you want people to actually read them.
